# Generated by Django 4.0.6 on 2024-06-06 20:33

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255, unique=True, verbose_name='Адрес дома')),
            ],
            options={
                'verbose_name': 'Дом',
                'verbose_name_plural': 'Дома',
                'ordering': ('address',),
            },
        ),
        migrations.CreateModel(
            name='Tariff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('hot', 'Горячая вода'), ('cold', 'Холодная вода'), ('property', 'Содержание общего имущества')], max_length=50, unique=True, verbose_name='Название')),
                ('price', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Цена')),
            ],
            options={
                'verbose_name': 'Тариф',
                'verbose_name_plural': 'Тарифы',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='ValueWaterMeter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.PositiveIntegerField(help_text='Введите показания до запятой', validators=[django.core.validators.MaxValueValidator(5, message='Показания должны содержать не более 5 символов')], verbose_name='Показания счетчика')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Дата и время показаний')),
            ],
            options={
                'verbose_name': 'Паказание счетчика',
                'verbose_name_plural': 'Паказания счетчика',
                'ordering': ('date',),
            },
        ),
        migrations.CreateModel(
            name='WaterMeter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(blank=True, max_length=50, null=True, verbose_name='Номер прибора')),
                ('tariff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='houses.tariff', verbose_name='Тариф')),
                ('value', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='houses.valuewatermeter', verbose_name='Показания счетчика')),
            ],
            options={
                'verbose_name': 'Счетчик воды',
                'verbose_name_plural': 'Счетчики воды',
                'ordering': ('value__date',),
                'default_related_name': 'water_meter',
            },
        ),
        migrations.CreateModel(
            name='Apartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField(verbose_name='Номер квартиры')),
                ('area', models.FloatField(verbose_name='Площадь квартиры')),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='houses.house')),
                ('water_meter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='houses.watermeter', verbose_name='Cчетчик воды')),
            ],
            options={
                'verbose_name': 'Квартира',
                'verbose_name_plural': 'Квартиры',
                'ordering': ('number',),
                'default_related_name': 'apartments',
            },
        ),
    ]
