# Generated by Django 4.0.6 on 2024-06-04 22:14

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Apartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('namber', models.PositiveSmallIntegerField(unique=True, verbose_name='Номер квартиры')),
                ('area', models.FloatField(verbose_name='Площадь квартиры')),
            ],
            options={
                'verbose_name': 'Квартира',
                'verbose_name_plural': 'Квартиры',
                'ordering': ('namber',),
                'default_related_name': 'apartment',
            },
        ),
        migrations.CreateModel(
            name='Tariff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
                ('units', models.CharField(max_length=10, verbose_name='Единица измерения')),
                ('price', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Цена')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время изменения тарифа')),
            ],
            options={
                'verbose_name': 'Тариф',
                'verbose_name_plural': 'Тарифы',
                'ordering': ('date',),
            },
        ),
        migrations.CreateModel(
            name='ValueWaterMeter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.PositiveIntegerField(help_text='Введите показания до запятой', validators=[django.core.validators.MaxValueValidator(5, message='Показания должны содержать не более 5 символов')], verbose_name='Показания счетчика')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время показаний')),
            ],
            options={
                'verbose_name': 'Паказание счетчика',
                'verbose_name_plural': 'Паказания счетчика',
                'ordering': ('date',),
            },
        ),
        migrations.CreateModel(
            name='WaterMeter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(blank=True, max_length=50, unique=True, verbose_name='Номер прибора')),
                ('type_water', models.CharField(choices=[('hot', 'Горячая'), ('cold', 'Холодная')], default='cold', max_length=50, verbose_name='Тип воды')),
                ('tariff', models.ManyToManyField(to='houses.tariff', verbose_name='Тариф')),
                ('value', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='houses.valuewatermeter', verbose_name='Показания счетчика')),
            ],
            options={
                'verbose_name': 'Счетчик воды',
                'verbose_name_plural': 'Счетчики воды',
                'ordering': ('value__date',),
                'default_related_name': 'water_meter',
            },
        ),
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255, verbose_name='Адрес дома')),
                ('apartment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='houses.apartment', verbose_name='Квартира')),
            ],
            options={
                'verbose_name': 'Дом',
                'verbose_name_plural': 'Дома',
                'ordering': ('address',),
                'default_related_name': 'houses',
            },
        ),
        migrations.AddField(
            model_name='apartment',
            name='water_meter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='houses.watermeter', verbose_name='Cчетчик воды'),
        ),
    ]
