# Generated by Django 4.0.6 on 2024-06-09 18:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watermeter',
            name='date',
            field=models.DateField(default=datetime.date(2024, 6, 9), verbose_name='Дата показаний'),
        ),
    ]
