# Generated by Django 4.0.6 on 2024-06-05 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tariff',
            name='name',
            field=models.CharField(choices=[('hot', 'Горячая вода'), ('cold', 'Холодная вода'), ('property', 'Содержание общего имущества')], max_length=50, unique=True, verbose_name='Название'),
        ),
    ]
