# Generated by Django 4.0.6 on 2024-06-05 21:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0002_alter_tariff_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watermeter',
            name='number',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Номер прибора'),
        ),
        migrations.RemoveField(
            model_name='watermeter',
            name='tariff',
        ),
        migrations.AddField(
            model_name='watermeter',
            name='tariff',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='houses.tariff', verbose_name='Тариф'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='watermeter',
            name='value',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='houses.valuewatermeter', verbose_name='Показания счетчика'),
        ),
    ]
