# Generated by Django 4.0.6 on 2024-06-05 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0003_alter_watermeter_number_remove_watermeter_tariff_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watermeter',
            name='number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Номер прибора'),
        ),
    ]
