# Generated by Django 4.0.6 on 2024-06-10 21:22

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0003_alter_watermeter_options_alter_watermeter_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='tariff_property',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='houses.tariff', verbose_name='Тариф общего имущества'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='watermeter',
            name='date',
            field=models.DateField(default=datetime.date(2024, 6, 11), verbose_name='Дата показаний'),
        ),
    ]
