# Generated by Django 4.0.6 on 2024-06-05 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0004_alter_watermeter_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='apartment',
            options={'default_related_name': 'apartments', 'ordering': ('number',), 'verbose_name': 'Квартира', 'verbose_name_plural': 'Квартиры'},
        ),
        migrations.RenameField(
            model_name='apartment',
            old_name='namber',
            new_name='number',
        ),
    ]
