# Generated by Django 4.0.6 on 2024-06-12 13:03

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0004_house_tariff_property_alter_watermeter_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartment',
            name='area',
            field=models.DecimalField(decimal_places=1, max_digits=3, verbose_name='Площадь квартиры'),
        ),
        migrations.AlterField(
            model_name='watermeter',
            name='date',
            field=models.DateField(default=datetime.date(2024, 6, 12), verbose_name='Дата показаний'),
        ),
        migrations.CreateModel(
            name='Rent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost_water', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Водоснабжение')),
                ('cost_property', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Содержание общего имущества')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Дата показаний')),
                ('apartment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='houses.apartment', verbose_name='Квартира')),
            ],
            options={
                'verbose_name': 'Квартплата',
                'verbose_name_plural': 'Квартплаты',
                'ordering': ('apartment',),
            },
        ),
    ]
